from typing import Dict, Any, List, Optional
from ..utils.validation import normalize_mine_id

CANONICAL_MOIL_MINES: Dict[str, Dict[str, Any]] = {
    "balaghat": {
        "id": "balaghat",
        "name": "Balaghat Mine",
        "shortName": "Balaghat",
        "mineType": "Underground Deep Shaft",
        "district": "Balaghat",
        "state": "Madhya Pradesh",
        "latitude": 21.84995,
        "longitude": 80.22672,
        "coordinatesDMS": "21°50'59.8\"N 80°13'36.2\"E",
        "elevation": "330m MSL",
        "oreGrade": "44.2% Mn (High Grade)",
        "baseGradeNum": 44.2,
        "productionTarget": 6200,
        "baselineProduction": 6200,
        "fleetCount": 32,
        "fleetSize": 32,
        "sensorCount": 184,
        "waterTableDepth": "-185m Level",
        "drainageBaselineM3h": 14.5,
        "maxDrainageCapacityM3h": 45.0,
        "rainfallSensitivity": 1.35,
        "crusherCapacityTPH": 280,
        "crusherHealthBase": 88,
        "crusherVibBase": 2.1,
        "crusherTempBase": 68,
        "fleetAvailabilityBase": 87.5,
        "haulDistanceKm": 2.8,
        "stockpileBufferT": 850,
        "shortfallRisk": "Low (12%)",
        "statusVariant": "telemetry",
        "languageOptions": ["en", "hi"],
        "unfcStatus": "UNFC-111 (Proved Mineral Reserve)",
        "reserve": {
            "provedTonnes": 14200000,
            "probableTonnes": 6800000,
            "strikeLengthKm": 3.4,
            "dipAngle": "72° North"
        }
    },
    "tirodi": {
        "id": "tirodi",
        "name": "Tirodi Mine",
        "shortName": "Tirodi",
        "mineType": "Opencast & Incline Shaft",
        "district": "Balaghat",
        "state": "Madhya Pradesh",
        "latitude": 21.68889,
        "longitude": 79.70278,
        "coordinatesDMS": "21°41'20.0\"N 79°42'10.0\"E",
        "elevation": "312m MSL",
        "oreGrade": "39.4% Mn (Medium Grade)",
        "baseGradeNum": 39.4,
        "productionTarget": 3100,
        "baselineProduction": 3100,
        "fleetCount": 24,
        "fleetSize": 24,
        "sensorCount": 112,
        "waterTableDepth": "-95m Level",
        "drainageBaselineM3h": 10.2,
        "maxDrainageCapacityM3h": 32.0,
        "rainfallSensitivity": 1.48,
        "crusherCapacityTPH": 180,
        "crusherHealthBase": 90,
        "crusherVibBase": 1.8,
        "crusherTempBase": 64,
        "fleetAvailabilityBase": 85.0,
        "haulDistanceKm": 3.4,
        "stockpileBufferT": 620,
        "shortfallRisk": "Low (15%)",
        "statusVariant": "telemetry",
        "languageOptions": ["en", "hi"],
        "unfcStatus": "UNFC-111 (Proved Mineral Reserve)",
        "reserve": {
            "provedTonnes": 6400000,
            "probableTonnes": 3200000,
            "strikeLengthKm": 2.6,
            "dipAngle": "65° South"
        }
    },
    "ukwa": {
        "id": "ukwa",
        "name": "Ukwa Mine",
        "shortName": "Ukwa",
        "mineType": "Underground Drift & Adit",
        "district": "Balaghat",
        "state": "Madhya Pradesh",
        "latitude": 21.97467,
        "longitude": 80.46000,
        "coordinatesDMS": "21°58'28.8\"N 80°27'36.0\"E",
        "elevation": "460m MSL",
        "oreGrade": "41.8% Mn (Low Phosphorus)",
        "baseGradeNum": 41.8,
        "productionTarget": 1850,
        "baselineProduction": 1850,
        "fleetCount": 18,
        "fleetSize": 18,
        "sensorCount": 96,
        "waterTableDepth": "-120m Level",
        "drainageBaselineM3h": 8.0,
        "maxDrainageCapacityM3h": 25.0,
        "rainfallSensitivity": 1.20,
        "crusherCapacityTPH": 140,
        "crusherHealthBase": 92,
        "crusherVibBase": 1.6,
        "crusherTempBase": 62,
        "fleetAvailabilityBase": 89.0,
        "haulDistanceKm": 2.1,
        "stockpileBufferT": 450,
        "shortfallRisk": "Low (9%)",
        "statusVariant": "telemetry",
        "languageOptions": ["en", "hi"],
        "unfcStatus": "UNFC-111 (Low-Phosphorus Ore Body)",
        "reserve": {
            "provedTonnes": 4800000,
            "probableTonnes": 2100000,
            "strikeLengthKm": 4.1,
            "dipAngle": "45° North"
        }
    },
    "munsar": {
        "id": "munsar",
        "name": "Munsar Mine",
        "shortName": "Munsar",
        "mineType": "Underground Deep Shaft",
        "district": "Nagpur",
        "state": "Maharashtra",
        "latitude": 21.39722,
        "longitude": 79.28889,
        "coordinatesDMS": "21°23'50.0\"N 79°17'20.0\"E",
        "elevation": "310m MSL",
        "oreGrade": "38.6% Mn (Standard Ferromanganese)",
        "baseGradeNum": 38.6,
        "productionTarget": 2400,
        "baselineProduction": 2400,
        "fleetCount": 20,
        "fleetSize": 20,
        "sensorCount": 108,
        "waterTableDepth": "-140m Level",
        "drainageBaselineM3h": 12.0,
        "maxDrainageCapacityM3h": 35.0,
        "rainfallSensitivity": 1.30,
        "crusherCapacityTPH": 160,
        "crusherHealthBase": 86,
        "crusherVibBase": 2.2,
        "crusherTempBase": 69,
        "fleetAvailabilityBase": 86.0,
        "haulDistanceKm": 2.5,
        "stockpileBufferT": 500,
        "shortfallRisk": "Low (14%)",
        "statusVariant": "telemetry",
        "languageOptions": ["en", "hi", "mr"],
        "unfcStatus": "UNFC-111 (Proved Mineral Reserve)",
        "reserve": {
            "provedTonnes": 5100000,
            "probableTonnes": 2400000,
            "strikeLengthKm": 2.2,
            "dipAngle": "70° South"
        }
    },
    "kandri": {
        "id": "kandri",
        "name": "Kandri Mine",
        "shortName": "Kandri",
        "mineType": "Semi-Mechanized Underground Shaft",
        "district": "Nagpur",
        "state": "Maharashtra",
        "latitude": 21.41944,
        "longitude": 79.26667,
        "coordinatesDMS": "21°25'10.0\"N 79°16'00.0\"E",
        "elevation": "318m MSL",
        "oreGrade": "42.5% Mn (High Grade Lumpy)",
        "baseGradeNum": 42.5,
        "productionTarget": 2800,
        "baselineProduction": 2800,
        "fleetCount": 22,
        "fleetSize": 22,
        "sensorCount": 118,
        "waterTableDepth": "-160m Level",
        "drainageBaselineM3h": 11.5,
        "maxDrainageCapacityM3h": 38.0,
        "rainfallSensitivity": 1.28,
        "crusherCapacityTPH": 190,
        "crusherHealthBase": 89,
        "crusherVibBase": 1.9,
        "crusherTempBase": 66,
        "fleetAvailabilityBase": 88.0,
        "haulDistanceKm": 2.3,
        "stockpileBufferT": 580,
        "shortfallRisk": "Low (11%)",
        "statusVariant": "telemetry",
        "languageOptions": ["en", "hi", "mr"],
        "unfcStatus": "UNFC-111 (Proved Lumpy Reserve)",
        "reserve": {
            "provedTonnes": 5800000,
            "probableTonnes": 2900000,
            "strikeLengthKm": 2.8,
            "dipAngle": "68° South-West"
        }
    },
    "gumgaon": {
        "id": "gumgaon",
        "name": "Gumgaon Mine",
        "shortName": "Gumgaon",
        "mineType": "Deep Vertical Shaft",
        "district": "Nagpur",
        "state": "Maharashtra",
        "latitude": 21.39167,
        "longitude": 79.01667,
        "coordinatesDMS": "21°23'30.0\"N 79°01'00.0\"E",
        "elevation": "298m MSL",
        "oreGrade": "43.8% Mn (Premium Grade)",
        "baseGradeNum": 43.8,
        "productionTarget": 3400,
        "baselineProduction": 3400,
        "fleetCount": 26,
        "fleetSize": 26,
        "sensorCount": 134,
        "waterTableDepth": "-210m Level",
        "drainageBaselineM3h": 16.0,
        "maxDrainageCapacityM3h": 50.0,
        "rainfallSensitivity": 1.42,
        "crusherCapacityTPH": 220,
        "crusherHealthBase": 87,
        "crusherVibBase": 2.0,
        "crusherTempBase": 67,
        "fleetAvailabilityBase": 86.5,
        "haulDistanceKm": 2.7,
        "stockpileBufferT": 700,
        "shortfallRisk": "Low (13%)",
        "statusVariant": "telemetry",
        "languageOptions": ["en", "hi", "mr"],
        "unfcStatus": "UNFC-111 (Deep High-Grade Shaft)",
        "reserve": {
            "provedTonnes": 7200000,
            "probableTonnes": 3600000,
            "strikeLengthKm": 3.1,
            "dipAngle": "75° South"
        }
    },
    "chikla": {
        "id": "chikla",
        "name": "Chikla Mine",
        "shortName": "Chikla",
        "mineType": "Underground Sub-Level Stoping",
        "district": "Bhandara",
        "state": "Maharashtra",
        "latitude": 21.55000,
        "longitude": 79.76667,
        "coordinatesDMS": "21°33'00.0\"N 79°46'00.0\"E",
        "elevation": "345m MSL",
        "oreGrade": "41.2% Mn (Siliceous Blend)",
        "baseGradeNum": 41.2,
        "productionTarget": 4100,
        "baselineProduction": 4100,
        "fleetCount": 28,
        "fleetSize": 28,
        "sensorCount": 142,
        "waterTableDepth": "-170m Level",
        "drainageBaselineM3h": 13.8,
        "maxDrainageCapacityM3h": 42.0,
        "rainfallSensitivity": 1.34,
        "crusherCapacityTPH": 240,
        "crusherHealthBase": 89,
        "crusherVibBase": 1.9,
        "crusherTempBase": 66,
        "fleetAvailabilityBase": 87.0,
        "haulDistanceKm": 2.9,
        "stockpileBufferT": 760,
        "shortfallRisk": "Low (12%)",
        "statusVariant": "telemetry",
        "languageOptions": ["en", "hi", "mr"],
        "unfcStatus": "UNFC-111 (Proved Stoping Deposit)",
        "reserve": {
            "provedTonnes": 8900000,
            "probableTonnes": 4200000,
            "strikeLengthKm": 3.6,
            "dipAngle": "60° North-East"
        }
    },
    "dongri-buzurg": {
        "id": "dongri-buzurg",
        "name": "Dongri Buzurg Mine",
        "shortName": "Dongri Buzurg",
        "mineType": "Large Opencast Bench & EMD Plant",
        "district": "Bhandara",
        "state": "Maharashtra",
        "latitude": 21.55833,
        "longitude": 79.68333,
        "coordinatesDMS": "21°33'30.0\"N 79°41'00.0\"E",
        "elevation": "315m MSL",
        "oreGrade": "40.5% Mn (Dioxide & Battery Grade)",
        "baseGradeNum": 40.5,
        "productionTarget": 5400,
        "baselineProduction": 5400,
        "fleetCount": 36,
        "fleetSize": 36,
        "sensorCount": 168,
        "waterTableDepth": "-110m Pit Floor",
        "drainageBaselineM3h": 18.5,
        "maxDrainageCapacityM3h": 60.0,
        "rainfallSensitivity": 1.55,
        "crusherCapacityTPH": 320,
        "crusherHealthBase": 91,
        "crusherVibBase": 1.7,
        "crusherTempBase": 63,
        "fleetAvailabilityBase": 88.5,
        "haulDistanceKm": 3.8,
        "stockpileBufferT": 1100,
        "shortfallRisk": "Low (10%)",
        "statusVariant": "telemetry",
        "languageOptions": ["en", "hi", "mr"],
        "unfcStatus": "UNFC-111 (High-Dioxide Opencast)",
        "reserve": {
            "provedTonnes": 11800000,
            "probableTonnes": 5400000,
            "strikeLengthKm": 4.5,
            "dipAngle": "55° South"
        }
    },
    "ramtek": {
        "id": "ramtek",
        "name": "Ramtek Operations",
        "shortName": "Ramtek",
        "mineType": "Mechanized Opencast & Infill",
        "district": "Nagpur",
        "state": "Maharashtra",
        "latitude": 21.40000,
        "longitude": 79.33333,
        "coordinatesDMS": "21°24'00.0\"N 79°20'00.0\"E",
        "elevation": "325m MSL",
        "oreGrade": "37.8% Mn (Standard Grade)",
        "baseGradeNum": 37.8,
        "productionTarget": 1600,
        "baselineProduction": 1600,
        "fleetCount": 16,
        "fleetSize": 16,
        "sensorCount": 84,
        "waterTableDepth": "-75m Level",
        "drainageBaselineM3h": 7.5,
        "maxDrainageCapacityM3h": 22.0,
        "rainfallSensitivity": 1.38,
        "crusherCapacityTPH": 120,
        "crusherHealthBase": 93,
        "crusherVibBase": 1.5,
        "crusherTempBase": 61,
        "fleetAvailabilityBase": 90.0,
        "haulDistanceKm": 2.4,
        "stockpileBufferT": 380,
        "shortfallRisk": "Low (8%)",
        "statusVariant": "telemetry",
        "languageOptions": ["en", "hi", "mr"],
        "unfcStatus": "UNFC-111 (Opencast Infill Zone)",
        "reserve": {
            "provedTonnes": 3400000,
            "probableTonnes": 1600000,
            "strikeLengthKm": 1.9,
            "dipAngle": "50° North"
        }
    },
    "bhandara": {
        "id": "bhandara",
        "name": "Bhandara Mine (Beldongri)",
        "shortName": "Bhandara",
        "mineType": "Underground & Opencast Cluster",
        "district": "Bhandara",
        "state": "Maharashtra",
        "latitude": 21.45000,
        "longitude": 79.51667,
        "coordinatesDMS": "21°27'00.0\"N 79°31'00.0\"E",
        "elevation": "305m MSL",
        "oreGrade": "38.2% Mn (Ferro-Grade)",
        "baseGradeNum": 38.2,
        "productionTarget": 1950,
        "baselineProduction": 1950,
        "fleetCount": 18,
        "fleetSize": 18,
        "sensorCount": 92,
        "waterTableDepth": "-85m Level",
        "drainageBaselineM3h": 8.5,
        "maxDrainageCapacityM3h": 28.0,
        "rainfallSensitivity": 1.32,
        "crusherCapacityTPH": 150,
        "crusherHealthBase": 91,
        "crusherVibBase": 1.7,
        "crusherTempBase": 63,
        "fleetAvailabilityBase": 88.0,
        "haulDistanceKm": 2.6,
        "stockpileBufferT": 420,
        "shortfallRisk": "Low (10%)",
        "statusVariant": "telemetry",
        "languageOptions": ["en", "hi", "mr"],
        "unfcStatus": "UNFC-111 (Proved Combined Deposit)",
        "reserve": {
            "provedTonnes": 3900000,
            "probableTonnes": 1800000,
            "strikeLengthKm": 2.3,
            "dipAngle": "62° South"
        }
    }
}

class MineService:
    @staticmethod
    def get_all_mines() -> List[Dict[str, Any]]:
        return list(CANONICAL_MOIL_MINES.values())

    @staticmethod
    def get_mine_by_id(mine_id: str) -> Dict[str, Any]:
        norm_id = normalize_mine_id(mine_id)
        mine = CANONICAL_MOIL_MINES[norm_id]
        
        # Assemble nested detail representation
        return {
            **mine,
            "telemetry": {
                "active_fleet": f"{int(mine['fleetCount']*0.88)}/{mine['fleetCount']} Units Online",
                "crusher_health": f"{mine['crusherHealthBase']}%",
                "water_table": mine["waterTableDepth"],
                "pumps_online": "4/4 Stage Submersibles"
            },
            "analytics": {
                "quota_achievement": "98.4%",
                "trend_mom": "+2.4%",
                "recovery_rate": "88.2%",
                "silica_level": "8.4% SiO₂"
            },
            "equipment": {
                "primary_crusher": f"{mine['crusherCapacityTPH']} TPH Jaw Crusher",
                "fleet_size": f"{mine['fleetCount']} Dumper Units",
                "submersible_pumps": f"{mine['maxDrainageCapacityM3h']} m³/h Matrix"
            },
            "reserve": mine["reserve"],
            "risks": {
                "shortfall": mine["shortfallRisk"],
                "geotechnical": "DGMS FoS 1.82 (Safe)",
                "water_inrush": "Controlled Pumping Rate"
            },
            "trust": {
                "bayesian_score": "95.8%",
                "iso_compliance": "ISO 22932 Certified"
            }
        }

mine_service = MineService()
